services:
  mongo:
    image: mongo
    ports:
      - '27017:27017'

  webhook:
    build: 
      context: .
      dockerfile: ./apps/webhook/Dockerfile
      target: development
    command: yarn run start:dev webhook
    env_file:
      - ./apps/webhook/.env
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/src/app
    restart: unless-stopped

  api-gateway:
    build:
      context: .
      dockerfile: ./apps/api-gateway/Dockerfile
      target: development
    command: yarn run start:dev api-gateway
    env_file:
      - ./apps/api-gateway/.env
    ports: 
      - '3001:3001'
    volumes:
      - .:/usr/src/app
    depends_on:
      - webhook
    restart: unless-stopped
      
  conversations:
    build:
      context: .
      dockerfile: ./apps/conversations/Dockerfile
      target: development
    command: yarn run start:dev conversations
    env_file:
      - ./apps/conversations/.env
    ports: 
      - '3002:3002'
    volumes:
      - .:/usr/src/app
    depends_on:
      - api-gateway
    restart: unless-stopped
